import XCTest
@testable import ContextContract

final class ScannerTests: XCTestCase {
    func testBulletsParagraphsSectionsAndLineNumbers() {
        let md = """
        # Title

        ## Project
        - first
          - nested
        1. numbered
        plain paragraph

        ```
        - inside a fence, ignored
        ```
        ## Rules
        * starred
        """
        let d = ContractScanner.scan(md)
        XCTAssertEqual(d.map(\.text), ["first", "nested", "numbered", "plain paragraph", "starred"])
        XCTAssertEqual(d.map(\.line), [4, 5, 6, 7, 13])
        XCTAssertEqual(d.map(\.section), ["Project", "Project", "Project", "Project", "Rules"])
    }

    func testEmptyAndWhitespaceOnlyInput() {
        XCTAssertTrue(ContractScanner.scan("").isEmpty)
        XCTAssertTrue(ContractScanner.scan("   \n\n# Only a heading\n").isEmpty)
        let report = PortabilityReport(markdown: "")
        XCTAssertEqual(report.total, 0)
        XCTAssertEqual(report.portableShare, 0)      // no division by zero
        XCTAssertEqual(report.lockInScore, 0)
        XCTAssertNil(report.dominantVendor)
    }

    func testChecklistAndUnknownBulletStyles() {
        XCTAssertEqual(ContractScanner.stripBullet("- [ ] todo"), "todo")
        XCTAssertEqual(ContractScanner.stripBullet("- [x] done"), "done")
        XCTAssertEqual(ContractScanner.stripBullet("12) twelve"), "twelve")
        XCTAssertEqual(ContractScanner.stripBullet("no bullet"), "no bullet")
    }
}

final class VendorSignatureTests: XCTestCase {
    func testDistinctiveToolNamesMatchAsWholeWords() {
        let sig = VendorSignature.signature(for: .claude)
        XCTAssertEqual(sig.matches(in: "Use Bash for shell work"), ["Bash"])
        XCTAssertEqual(sig.matches(in: "Bashful people"), [])
        XCTAssertEqual(sig.matches(in: "a bash script"), [])      // case-sensitive for tools
    }

    func testAmbiguousToolNamesNeedCodeOrTheWordTool() {
        let sig = VendorSignature.signature(for: .claude)
        XCTAssertEqual(sig.matches(in: "Read the full output before editing"), [])
        XCTAssertEqual(sig.matches(in: "Use the Read tool for files"), ["Read tool"])
        XCTAssertEqual(sig.matches(in: "Prefer `Edit` over rewriting"), ["`Edit`"])
    }

    func testNamesAreWholeWordsAndHyphenAware() {
        let sig = VendorSignature.signature(for: .claude)
        XCTAssertEqual(sig.matches(in: "Ask Claude first"), ["Claude"])
        XCTAssertEqual(sig.matches(in: "install claude-agent-acp"), [])
        XCTAssertEqual(sig.matches(in: "the claude binary"), [])       // proper nouns only
        XCTAssertEqual(sig.matches(in: "Claude Code handles this"), ["Claude Code"])
    }

    func testPathsAbsorbTheNameInsideThem() {
        let sig = VendorSignature.signature(for: .claude)
        XCTAssertEqual(sig.matches(in: "Skills live in `.claude/skills/`"), [".claude/"])
        XCTAssertEqual(sig.matches(in: "Edit CLAUDE.md to change this"), ["CLAUDE.md"])
    }

    func testOtherVendors() {
        XCTAssertEqual(VendorSignature.signature(for: .codex).matches(in: "use `apply_patch` when running as Codex"), ["Codex", "apply_patch"])
        XCTAssertEqual(VendorSignature.signature(for: .gemini).matches(in: "run_shell_command needs a cd"), ["run_shell_command"])
        XCTAssertEqual(VendorSignature.signature(for: .cursor).matches(in: "move the cursor down"), [])
        XCTAssertEqual(VendorSignature.signature(for: .cursor).matches(in: "rules live in .cursor/rules"), [".cursor/rules"])
        XCTAssertEqual(VendorSignature.signature(for: .copilot).matches(in: "see .github/copilot-instructions.md"), [".github/copilot-instructions.md"])
    }
}

final class EnforcementTests: XCTestCase {
    func testPermissionGate() {
        XCTAssertEqual(EnforcementDetector.detect(.permissionGate, in: "Never run `git push --force`."), "Never run")
        XCTAssertEqual(EnforcementDetector.detect(.permissionGate, in: "Do not commit; leave commits to the human."), "Do not commit")
        XCTAssertEqual(EnforcementDetector.detect(.permissionGate, in: "Ask before deleting any file."), "Ask before")
        XCTAssertEqual(EnforcementDetector.detect(.permissionGate, in: "Never delete branches without asking."), "Never delete")
        XCTAssertNil(EnforcementDetector.detect(.permissionGate, in: "never call URLSession from a view"))   // convention, not a permission
    }

    func testPathGuardNeedsAVerbAndAPath() {
        XCTAssertEqual(EnforcementDetector.detect(.pathGuard, in: "Never modify `Packages/*/Package.resolved` by hand."),
                       "Never modify … `Packages/*/Package.resolved`")
        XCTAssertNil(EnforcementDetector.detect(.pathGuard, in: "Never modify the tone of error messages."))
        XCTAssertNil(EnforcementDetector.detect(.pathGuard, in: "Package.resolved is regenerated by SwiftPM."))
    }

    func testBuildGate() {
        XCTAssertEqual(EnforcementDetector.detect(.buildGate, in: "Always run `swift test` before you say a task is done."), "Always run")
        XCTAssertEqual(EnforcementDetector.detect(.buildGate, in: "Run the tests before opening a PR."), "Run the tests before")
        XCTAssertEqual(EnforcementDetector.detect(.buildGate, in: "The build must pass on CI."), "must pass")
        XCTAssertNil(EnforcementDetector.detect(.buildGate, in: "When a build fails, read the full `xcodebuild` output before changing anything."))
    }

    func testSecretRedactionNeedsVocabularyAndFraming() {
        XCTAssertEqual(EnforcementDetector.detect(.secretRedaction, in: "Never print or log any API key."), "Never … API key")
        XCTAssertNil(EnforcementDetector.detect(.secretRedaction, in: "API keys are loaded from the keychain at launch."))
        XCTAssertEqual(EnforcementDetector.detect(.secretRedaction, in: "Do not paste credentials into PR descriptions."), "Do not … credentials")
        XCTAssertNil(EnforcementDetector.detect(.secretRedaction, in: "Do not waste context tokens re-reading files."))   // "tokens" alone is not a secret
    }
}

final class PlacementTests: XCTestCase {
    func testEnforcementBeatsVendorWording() {
        let d = Directive(line: 1, section: nil, text: "Never run Bash `rm -rf`; use the Task tool instead.")
        XCTAssertEqual(d.placement, .protocolLayer([.permissionGate]))
        XCTAssertEqual(d.vendorSignals.count, 2)
        XCTAssertTrue(d.isVendorEnforced)
    }

    func testMultipleEnforcementKindsAreOrderedBySeverity() {
        let d = Directive(line: 1, section: nil, text: "Never modify `Secrets/keys.plist`; never run scripts that print an API key.")
        XCTAssertEqual(d.placement, .protocolLayer([.secretRedaction, .pathGuard, .permissionGate]))
    }

    func testMultiVendorLineGoesToTheVendorWithMostEvidenceThenDeclarationOrder() {
        let mostEvidence = Directive(line: 1, section: nil, text: "Gemini: use `run_shell_command`; Claude is fine as is.")
        XCTAssertEqual(mostEvidence.placement, .vendorOverlay(.gemini))
        let tie = Directive(line: 2, section: nil, text: "Works with Claude or Codex.")
        XCTAssertEqual(tie.placement, .vendorOverlay(.claude))   // declaration order breaks the tie, on purpose
    }

    func testPortableWhenNothingMatches() {
        let d = Directive(line: 1, section: nil, text: "Prefer value types; view models are `@Observable` classes.")
        XCTAssertEqual(d.placement, .portable)
        XCTAssertTrue(d.signals.isEmpty)
    }
}

final class FixtureTests: XCTestCase {
    let report = Fixture.report

    func testHeadlineNumbersArePinned() {
        XCTAssertEqual(report.total, 28)
        XCTAssertEqual(report.portable, 12)
        XCTAssertEqual(report.vendorBound, [.claude: 7, .codex: 1, .gemini: 1])
        XCTAssertEqual(report.vendorBoundTotal, 9)
        XCTAssertEqual(report.protocolLayer, 7)
        XCTAssertEqual(report.enforcementCounts, [.permissionGate: 3, .pathGuard: 1, .buildGate: 1, .secretRedaction: 2])
        XCTAssertEqual(report.dominantVendor, .claude)
        XCTAssertEqual(report.portableShare, 12.0 / 28.0, accuracy: 1e-9)
        XCTAssertEqual(report.lockInScore, 9.0 / 28.0, accuracy: 1e-9)
        XCTAssertEqual(report.enforcementByProseShare, 7.0 / 28.0, accuracy: 1e-9)
    }

    func testEveryRuleInTheRulesSectionIsAnEnforcementClaim() {
        let rules = report.directives.filter { $0.section == "Rules" }
        XCTAssertEqual(rules.count, 7)
        XCTAssertTrue(rules.allSatisfy { !$0.placement.enforcements.isEmpty })
    }

    func testTheOnlyEnforcedRuleIsEnforcedByOneVendorsHook() {
        XCTAssertEqual(report.vendorEnforced.map(\.line), [38])
        XCTAssertEqual(report.vendorEnforced.first?.vendorSignals.compactMap(\.vendor), [.claude, .claude])
    }

    func testCoverageBeforeAndAfter() {
        let coverage = Coverage(report: report, sourceFile: Fixture.sourceFile)
        XCTAssertEqual(coverage.agentsReadingAsWritten, 1)
        XCTAssertEqual(coverage.agentsReadingCompiled, 5)
        let byVendor = Dictionary(uniqueKeysWithValues: coverage.rows.map { ($0.vendor, $0) })
        XCTAssertEqual(byVendor[.claude]?.asWritten, 28)
        XCTAssertEqual(byVendor[.codex]?.asWritten, 0)
        XCTAssertEqual(byVendor[.gemini]?.asWritten, 0)
        XCTAssertEqual(byVendor[.claude]?.compiled, 26)   // 12 portable + 7 informational + 7 Claude lines
        XCTAssertEqual(byVendor[.codex]?.compiled, 20)    // 12 + 7 + 1
        XCTAssertEqual(byVendor[.gemini]?.compiled, 20)
        XCTAssertEqual(byVendor[.cursor]?.compiled, 19)
        XCTAssertEqual(byVendor[.copilot]?.compiled, 19)
        XCTAssertEqual(byVendor[.codex]?.compiledSupport, .native)
        XCTAssertFalse(byVendor[.claude]?.compiledSupport?.isNative ?? true)
    }
}

final class CompilerTests: XCTestCase {
    let output = ContractCompiler.compile(Fixture.report, project: Fixture.projectName)

    func testFilesWritten() {
        XCTAssertEqual(output.files.map(\.path), ["AGENTS.md", "CLAUDE.md", "GEMINI.md", "ENFORCEMENT.md"])
    }

    func testAgentsMDHoldsPortableLinesAndNoVendorLines() {
        let agents = output.files[0].contents
        for d in Fixture.report.directives where d.placement.isPortable {
            XCTAssertTrue(agents.contains("- \(d.text)"), d.text)
        }
        for d in Fixture.report.directives(placedIn: .claude) {
            XCTAssertFalse(agents.contains(d.text), d.text)
        }
        XCTAssertTrue(agents.contains("## Codex only"))
        XCTAssertTrue(agents.contains("## Enforced by the permission layer (informational)"))
    }

    func testShimsComeFirst() {
        XCTAssertTrue(output.files[1].contents.hasPrefix("@AGENTS.md\n"))
        XCTAssertTrue(output.files[2].contents.hasPrefix("@./AGENTS.md\n"))
        XCTAssertTrue(output.files[1].contents.contains("Use `MultiEdit` for multi-hunk changes"))
    }

    func testEnforcementPlanHasOneRowPerClaim() {
        XCTAssertEqual(output.enforcement.count, 7)
        let table = output.files[3].contents
        XCTAssertEqual(table.components(separatedBy: "| not enforced |").count - 1, 7)
        XCTAssertTrue(table.contains("session/request_permission"))
    }

    func testEmptyReportStillCompiles() {
        let out = ContractCompiler.compile(PortabilityReport(markdown: ""), project: "Empty")
        XCTAssertEqual(out.files.map(\.path), ["AGENTS.md", "CLAUDE.md", "GEMINI.md", "ENFORCEMENT.md"])
        XCTAssertTrue(out.files[3].contents.contains("No enforcement claims found."))
        XCTAssertTrue(out.enforcement.isEmpty)
    }
}
